fotoblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

import authentication.views
import blog.views

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', include('authentication.urls')),
    # mempersingkat kode tanpa harus membuat LoginPageView di views
    path('', LoginView.as_view(
        template_name='authentication/login.html',
        redirect_authenticated_user=True,
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html',
    ), name='password_change'),
    path('change-password-done/', PasswordChangeDoneView.as_view(
        template_name='authentication/password_change_done.html',
    ), name='password_change_done'),
    path('signup/', authentication.views.signup_page, name='signup'),
    path('profile-photo/upload', authentication.views.upload_profile_photo, name='upload_profile_photo'),
    # path("", authentication.views.login_page, name="login_fbv"),
    # path("", authentication.views.LoginPageView.as_view(), name='login'),
    # path("logout/", authentication.views.logout_user, name='logout'),
    path("home/", blog.views.home, name='home'),
    path('photo-feed/', blog.views.photo_feed, name='photo_feed'),
    path('photo/upload/', blog.views.photo_upload, name='photo_upload'),
    path('blog/create', blog.views.blog_and_photo_upload, name='blog_create'),
    path("blog/<int:blog_id>/", blog.views.view_blog, name='view_blog'),
    path('blog/<int:blog_id>/edit', blog.views.edit_blog, name='edit_blog'),
    path('photo/upload-multiple/', blog.views.create_multiple_photos, name='create_multiple_photos'),
    path('follow-users/', blog.views.follow_users, name='follow_users'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

blog/models.py
from django.conf import settings
from django.db import models
from PIL import Image


class Photo(models.Model):
    image = models.ImageField()
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        # save the resized image to the file system
        # this is not the model save method!
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()


class Blog(models.Model):
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    word_count = models.IntegerField(null=True)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributors')

    def _get_word_count(self):
        return len(self.content.split(' '))

    def save(self, *args, **kwargs):
        self.word_count = self._get_word_count()
        super().save(*args, **kwargs)


class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ('contributor', 'blog')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FotoBlog</title>
      <link rel="stylesheet" href="{% static 'app.css' %}">
  </head>
  <body>
  <div class="sidebar">
    <h1>Foto Blog</h1>
    {% if user.is_authenticated %}
        <p>Hey {{ user }}</p>
        {% if user.profile_photo %}
            <img class="avatar" src="{{ user.profile_photo.url }}" alt="">
        {% else %}
            <img src="{% static 'images/default_profile.png' %}" alt="" class="avatar">
        
        {% endif %}
        <p><a href="{% url 'home' %}">Home</a></p>
        {% if perms.blog.add_blog %}

            <p><a href="{% url 'blog_create' %}">Create Blog Post</a></p>

        {% endif %}
        {% if perms.blog.add_photo %}
            <p><a href="{% url 'photo_upload' %}">Upload Photo</a></p>
            <p><a href="{% url 'create_multiple_photos' %}">Upload Multiple Photos</a></p>
        {% endif %}
        <p><a href="{% url 'follow_users' %}">Follow Users</a></p>
        <p><a href="{% url 'upload_profile_photo' %}">Change Profile Photo</a></p>


        <p>Want to <a href="{%  url 'password_change' %}">change your password</a></p>
        <p>You are logged in as {{ request.user }}. Click here to <a href="{% url 'logout' %}">Logout</a></p>

    {% endif %}
  </div>
  <div class="main">
      {% block content %} {% endblock content %}

  </div>
  </body>
</html>